<a href="https://colab.research.google.com/github/kojiyam/information-transmission-engineering/blob/main/jd1_dB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# デシベル

実行: Shift+Enter

In [2]:
import numpy as np
np.random.seed(1) # 乱数のseedは固定

#import matplotlib.pyplot as plt
#plt.style.use('dark_background') # for dark-mode
#plt.rcParams["font.size"] = 16

In [3]:
10*np.log10(2)

3.010299956639812

In [6]:
x = np.array([1,2,4,5,8,10,20,100])
print(x)

[  1   2   4   5   8  10  20 100]


In [8]:
np.set_printoptions(precision=8) # デフォルトの小数点以下の表示桁数
print( 10*np.log10(x) )

[ 0.          3.01029996  6.02059991  6.98970004  9.03089987 10.
 13.01029996 20.        ]


In [9]:
np.set_printoptions(precision=0)
print( 10*np.log10(x) )

[ 0.  3.  6.  7.  9. 10. 13. 20.]


## リニアスケールに戻す

$10^{(x)_\mathrm{dB}/10}$

In [11]:
x_dB = np.array([13,17,20])
print( 10**(x_dB/10) )

[ 20.  50. 100.]
